version: '3.1'

services:
  nginx:
    build: ./nginx
    depends_on:
      - api
      - client
    environment:
      VIRTUAL_HOST: dev-bingo.local
      VIRTUAL_PORT: 8080
    expose:
      - 8080
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/mongodb:/data/db
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: dev-bingo-proxy