version: '2'

services:
  nginx:
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
      - client
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  api:
    build:
      dockerfile: Dockerfile.prod
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - ~/mongodb:/data/db